[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DOLPHOT-JWST"
authors = [{name = "Dan Weisz", email = "dan.weisz@berkeley.edu"}]
dynamic = ["version", "description"]
